[build]
  # Directory with the serverless functions code
  functions = "netlify/functions"
  # Directory to publish - use the current directory instead of build
  publish = "."
  # No build command needed since we're publishing the current directory
  command = "echo 'Skipping build step - publishing current directory'"

# Configure functions with longer timeout
[functions]
  # Set default timeout for all functions
  timeout = 26

# Configure api-proxy as a background function for longer running requests
[functions.api-proxy]
  background = true

[build.environment]
  TARGET_API_ENDPOINT = "http://130.61.212.178:3000/api/chat/completions"

# Redirect and rewrite rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Only redirect for paths that don't exist
  force = false

# Environment variable configuration
[context.production.environment]
  # Production environment variables can be set in the Netlify UI
  NODE_ENV = "production"

[context.deploy-preview.environment]
  # Preview environment variables
  NODE_ENV = "production"

# Dev server settings for netlify dev
[dev]
  framework = "#static"
  command = "python -m http.server 8888"
  port = 8888
  targetPort = 8888
  publish = "."
  autoLaunch = true
